#!/bin/sh

# Call me from /usr/share/xsessions/

wmname LG3D
nvidia-settings -l
parcellite &
gnome-sound-applet &
xcompmgr &
nm-applet &
nitrogen --restore &
dropbox start &
xmodmap ~/.xmodmap &

exec qtile
